# Generated by Django 4.1.2 on 2022-10-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
